# Basic Python

## 1. Split this string

In [11]:
s = "Hi there Sam!"

In [12]:
a = s.split(" ")
for i in a:
    print(i)

Hi
there
Sam!

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [13]:
planet = "Earth"
diameter = 12742

In [14]:
print("The diameter of {p} is {d} kilometers.".format(p=planet, d=diameter))

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [16]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [17]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [18]:
array1 = np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [19]:
array2 = np.full(10, 5)
print(array2)

[5 5 5 5 5 5 5 5 5 5]

## 5. Create an array of all the even integers from 20 to 35

In [20]:
array3 = np.arange(20, 35, 2)
print(array3)

[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
array4 = np.arange(0,9).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd
df = pd.DataFrame()
df['Name'] = ['Ryland Grace', 'Beatrice', 'Paul Atreides']
df['Age'] = [32, 16, 18]
print(df)

            Name  Age
0   Ryland Grace   32
1       Beatrice   16
2  Paul Atreides   18

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
dates = pd.date_range(start='2023-01-01', end='2023-02-10')
for i in dates:
  print(i.date())

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [27]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [29]:
dataframe = pd.DataFrame(lists, columns =['index', 'alphabet', 'numbers'])
print(dataframe)

   index alphabet  numbers
0      1      aaa       22
1      2      bbb       25
2      3      ccc       24